name: 'Hello World'
description: 'Greet someone'
inputs:
  context:  # id of input
    description: 'Who to greet'
    required: false
runs:
  using: "composite"
  steps:
    - name: Print context
      run: echo "Title= $CONTEXT" | jq -r ".pull_request.title"
      shell: bash
      env:
        CONTEXT: ${{ inputs.context }}

    - name: Set GitHub Path
      run: echo "$GITHUB_ACTION_PATH" >> $GITHUB_PATH
      shell: bash
      env:
        GITHUB_ACTION_PATH: ${{ github.action_path }}

    - name: Run goodbye.sh
      run: goodbye.sh
      shell: bash
      env:
        GITHUB_CONTEXT: ${{ inputs.context }}

