# action.yml
name: 'GitHub Action Peeker'
description: 'Peek into the env passed to action'
inputs:
  context:  # id of input
    description: 'GitHub context'
    required: true
    default: $GITHUB_CONTEXT
outputs:
  title: # id of output
    description: 'Some output var to peek'
    value: ${{ steps.output-context.outputs.title}}
runs:
  using: 'composite'
  steps:
    - name: output-context
      run: |
        $TITLE=$($INPUT_CONTEXT | jq -r ".event.pull_request.title")
        echo "title=$TITLE" >> $GITHUB_OUTPUT
      shell: bash