# action.yml
name: 'GitHub Action Peeker'
description: 'Peek into the env passed to action'
runs:
  using: 'composite'
  steps:
    - name: check-pr-title-for-jira-issue
      run: ./check-pr-title.sh
      shell: bash