name: 'Hello World'
description: 'Greet someone'
inputs:
  context:  # id of input
    description: 'Who to greet'
    required: false
runs:
  using: "composite"
  steps:
    - name: Print context
      run: echo $CONTEXT"
      shell: bash
      env:
        CONTEXT: ${{ inputs.context }}

    - name: Run goodbye.sh
      run: goodbye.sh
      shell: bash
      env:
        GITHUB_CONTEXT: ${{ inputs.context }}

